
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: WebService_SpringBoot
    description: Aplicação.
    author: Wenio Santana
    version: '@project.version@'
spring:
  profiles:
    active: dev